name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        continue-on-error: false

      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Run linting
        run: npx nx affected -t lint
        continue-on-error: false

      - name: Run tests
        run: npx nx affected -t test
        continue-on-error: false

      - name: Build applications
        run: npx nx affected -t build
        continue-on-error: false

      - name: Check build status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Build completed successfully"
            exit 0
          else
            echo "Build failed"
            exit 1
          fi

      - name: Report build status
        if: always()
        run: |
          echo "Build Status: ${{ job.status }}"
          echo "Build completed at: $(date)"
